name: Synopsys SAST (Polaris) - Plugin
on:
  workflow_dispatch:

jobs:
  polaris:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Synopsys Action (Polaris SAST)
        uses: synopsys-sig/synopsys-action@v1
        with:
          polaris_server_url: ${{ secrets.POLARIS_SERVER_URL }}
          polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          polaris_application_name: juice-shop
          polaris_project_name: juice-shop
